/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as CartCartIdRouteImport } from './routes/cart.$cartId'
import { Route as ContactIndexRouteImport } from './routes/contact.index'
import { Route as ContactThreadIdRouteImport } from './routes/contact.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CartCartIdRoute = CartCartIdRouteImport.update({
  id: '/cart/$cartId',
  path: '/cart/$cartId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContactRoute,
} as any)
const ContactThreadIdRoute = ContactThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ContactRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/cart/$cartId': typeof CartCartIdRoute
  '/contact/$threadId': typeof ContactThreadIdRoute
  '/contact/': typeof ContactIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/api/chat': typeof ApiChatRoute
  '/cart/$cartId': typeof CartCartIdRoute
  '/contact/$threadId': typeof ContactThreadIdRoute
  '/contact': typeof ContactIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/cart/$cartId': typeof CartCartIdRoute
  '/contact/$threadId': typeof ContactThreadIdRoute
  '/contact/': typeof ContactIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalog'
    | '/contact'
    | '/api/chat'
    | '/cart/$cartId'
    | '/contact/$threadId'
    | '/contact/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/catalog'
    | '/api/chat'
    | '/cart/$cartId'
    | '/contact/$threadId'
    | '/contact'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalog'
    | '/contact'
    | '/api/chat'
    | '/cart/$cartId'
    | '/contact/$threadId'
    | '/contact/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CatalogRoute: typeof CatalogRoute
  ContactRoute: typeof ContactRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  CartCartIdRoute: typeof CartCartIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/$cartId': {
      id: '/cart/$cartId'
      path: '/cart/$cartId'
      fullPath: '/cart/$cartId'
      preLoaderRoute: typeof CartCartIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof ContactRoute
    }
    '/contact/$threadId': {
      id: '/contact/$threadId'
      path: '/$threadId'
      fullPath: '/contact/$threadId'
      preLoaderRoute: typeof ContactThreadIdRouteImport
      parentRoute: typeof ContactRoute
    }
  }
}

interface ContactRouteChildren {
  ContactThreadIdRoute: typeof ContactThreadIdRoute
  ContactIndexRoute: typeof ContactIndexRoute
}

const ContactRouteChildren: ContactRouteChildren = {
  ContactThreadIdRoute: ContactThreadIdRoute,
  ContactIndexRoute: ContactIndexRoute,
}

const ContactRouteWithChildren =
  ContactRoute._addFileChildren(ContactRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CatalogRoute: CatalogRoute,
  ContactRoute: ContactRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  CartCartIdRoute: CartCartIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
